// src/models/employees.ts
export type EmploymentType = 'FullTime' | 'PartTime' | 'Contract' | 'Intern';
export type Department =
  | 'Engineering'
  | 'HR'
  | 'Sales'
  | 'Marketing'
  | 'Finance'
  | 'Operations'
  | 'IT'
  | 'CustomerSuccess'
  | 'Product'
  | 'Legal';

export interface Employee {
  id: string;
  name: string;
  department: Department;
  title: string;
  joinedOn: string; // ISO date (YYYY-MM-DD)
  leftOn: string | null; // null means still employed
  employmentType: EmploymentType;
  location: { city: string; country: string };
  managerId: string | null; // id of the manager or null
}

export const employees: Employee[] = [
  // --- Managers / Leads ---
  {
    id: 'EMP0001',
    name: 'Ahsan Khan',
    department: 'Engineering',
    title: 'Head of Engineering',
    joinedOn: '2017-03-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0002',
    name: 'Sara Malik',
    department: 'HR',
    title: 'HR Manager',
    joinedOn: '2018-06-01',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0003',
    name: 'Bilal Ahmed',
    department: 'Sales',
    title: 'Sales Director',
    joinedOn: '2016-09-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0004',
    name: 'Nadia Rehman',
    department: 'Finance',
    title: 'Finance Manager',
    joinedOn: '2019-01-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0005',
    name: 'Imran Ali',
    department: 'Operations',
    title: 'Operations Manager',
    joinedOn: '2017-11-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0006',
    name: 'Farah Sheikh',
    department: 'Marketing',
    title: 'Marketing Lead',
    joinedOn: '2020-02-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0007',
    name: 'Usman Javed',
    department: 'IT',
    title: 'IT Manager',
    joinedOn: '2018-08-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0008',
    name: 'Hira Qureshi',
    department: 'CustomerSuccess',
    title: 'Customer Success Lead',
    joinedOn: '2019-04-22',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0009',
    name: 'Kamran Zafar',
    department: 'Product',
    title: 'Head of Product',
    joinedOn: '2017-12-01',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: null,
  },
  {
    id: 'EMP0010',
    name: 'Zainab Noor',
    department: 'Legal',
    title: 'Lead Legal Counsel',
    joinedOn: '2021-01-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: null,
  },

  // --- Engineering ---
  {
    id: 'EMP0011',
    name: 'Muhammad Ali',
    department: 'Engineering',
    title: 'Senior Software Engineer',
    joinedOn: '2019-07-01',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0012',
    name: 'Ayesha Siddiqui',
    department: 'Engineering',
    title: 'Software Engineer',
    joinedOn: '2021-10-11',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0013',
    name: 'Hamza Yousaf',
    department: 'Engineering',
    title: 'Junior Software Engineer',
    joinedOn: '2023-05-08',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0014',
    name: 'Fatima Tariq',
    department: 'Engineering',
    title: 'QA Engineer',
    joinedOn: '2018-03-19',
    leftOn: '2022-12-31',
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0033',
    name: 'Maha Saeed',
    department: 'Engineering',
    title: 'Data Engineer',
    joinedOn: '2020-09-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0034',
    name: 'Arsalan Siddiqui',
    department: 'Engineering',
    title: 'DevOps Engineer',
    joinedOn: '2017-10-02',
    leftOn: '2023-09-15',
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },

  // --- HR ---
  {
    id: 'EMP0015',
    name: 'Salman Iqbal',
    department: 'HR',
    title: 'HR Generalist',
    joinedOn: '2020-07-06',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0002',
  },
  {
    id: 'EMP0016',
    name: 'Mehwish Raza',
    department: 'HR',
    title: 'Recruiter',
    joinedOn: '2022-01-24',
    leftOn: null,
    employmentType: 'Contract',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0002',
  },
  {
    id: 'EMP0037',
    name: 'Iqra Jaleel',
    department: 'HR',
    title: 'People Operations Specialist',
    joinedOn: '2023-07-17',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0002',
  },

  // --- Sales ---
  {
    id: 'EMP0017',
    name: 'Umar Farooq',
    department: 'Sales',
    title: 'Account Executive',
    joinedOn: '2019-09-02',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0018',
    name: 'Areeba Khan',
    department: 'Sales',
    title: 'Sales Associate',
    joinedOn: '2022-06-13',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0019',
    name: 'Danish Saeed',
    department: 'Sales',
    title: 'Sales Intern',
    joinedOn: '2024-06-01',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0003',
  },

  // --- Finance ---
  {
    id: 'EMP0020',
    name: 'Saba Gul',
    department: 'Finance',
    title: 'Accountant',
    joinedOn: '2020-03-16',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0004',
  },
  {
    id: 'EMP0021',
    name: 'Ali Raza',
    department: 'Finance',
    title: 'Financial Analyst',
    joinedOn: '2021-09-27',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0004',
  },
  {
    id: 'EMP0036',
    name: 'Saqib Latif',
    department: 'Finance',
    title: 'Payroll Specialist',
    joinedOn: '2018-12-03',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0004',
  },

  // --- Operations ---
  {
    id: 'EMP0022',
    name: 'Maryam Arif',
    department: 'Operations',
    title: 'Operations Analyst',
    joinedOn: '2018-05-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0005',
  },
  {
    id: 'EMP0023',
    name: 'Hassan Nadeem',
    department: 'Operations',
    title: 'Supply Chain Coordinator',
    joinedOn: '2022-11-07',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0005',
  },
  {
    id: 'EMP0038',
    name: 'Rehan Qureshi',
    department: 'Operations',
    title: 'Warehouse Supervisor',
    joinedOn: '2016-04-25',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0005',
  },

  // --- Marketing ---
  {
    id: 'EMP0024',
    name: 'Noor Fatima',
    department: 'Marketing',
    title: 'Content Strategist',
    joinedOn: '2020-08-24',
    leftOn: '2024-03-31',
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0025',
    name: 'Ahmed Rauf',
    department: 'Marketing',
    title: 'SEO Specialist',
    joinedOn: '2021-04-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0035',
    name: 'Nida Aftab',
    department: 'Marketing',
    title: 'Social Media Manager',
    joinedOn: '2024-01-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0006',
  },

  // --- IT ---
  {
    id: 'EMP0026',
    name: 'Rabia Butt',
    department: 'IT',
    title: 'Systems Administrator',
    joinedOn: '2019-02-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0007',
  },
  {
    id: 'EMP0027',
    name: 'Junaid Iqbal',
    department: 'IT',
    title: 'Helpdesk Technician',
    joinedOn: '2023-01-09',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0007',
  },
  {
    id: 'EMP0039',
    name: 'Amina Aziz',
    department: 'IT',
    title: 'Security Analyst',
    joinedOn: '2022-09-19',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0007',
  },

  // --- Customer Success ---
  {
    id: 'EMP0028',
    name: 'Saira Mehmood',
    department: 'CustomerSuccess',
    title: 'Customer Success Manager',
    joinedOn: '2019-10-21',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0008',
  },
  {
    id: 'EMP0029',
    name: 'Taha Siddiq',
    department: 'CustomerSuccess',
    title: 'Support Specialist',
    joinedOn: '2022-02-28',
    leftOn: null,
    employmentType: 'PartTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0008',
  },
  {
    id: 'EMP0040',
    name: 'Hasan Ali',
    department: 'CustomerSuccess',
    title: 'Onboarding Specialist',
    joinedOn: '2020-11-09',
    leftOn: '2022-05-31',
    employmentType: 'Contract',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0008',
  },

  // --- Product ---
  {
    id: 'EMP0030',
    name: 'Asad Mehmood',
    department: 'Product',
    title: 'Product Manager',
    joinedOn: '2018-07-30',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0009',
  },
  {
    id: 'EMP0031',
    name: 'Hiba Noman',
    department: 'Product',
    title: 'UX Researcher',
    joinedOn: '2021-12-06',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0009',
  },

  // --- Legal ---
  {
    id: 'EMP0032',
    name: 'Zohaib Anwar',
    department: 'Legal',
    title: 'Paralegal',
    joinedOn: '2021-03-22',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0010',
  },

  {
    id: 'EMP0041',
    name: 'Saima Rizwan',
    department: 'Engineering',
    title: 'Frontend Developer',
    joinedOn: '2022-08-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0042',
    name: 'Omar Sheikh',
    department: 'Engineering',
    title: 'Backend Developer',
    joinedOn: '2021-11-03',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0043',
    name: 'Aisha Khan',
    department: 'Engineering',
    title: 'Mobile App Developer',
    joinedOn: '2023-02-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0044',
    name: 'Fahad Ali',
    department: 'Engineering',
    title: 'Full Stack Developer',
    joinedOn: '2020-05-12',
    leftOn: '2023-11-30',
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0045',
    name: 'Zara Ahmed',
    department: 'Engineering',
    title: 'UI/UX Developer',
    joinedOn: '2022-01-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0046',
    name: 'Tariq Mahmood',
    department: 'Engineering',
    title: 'Senior DevOps Engineer',
    joinedOn: '2019-08-25',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0047',
    name: 'Nida Hassan',
    department: 'Engineering',
    title: 'QA Automation Engineer',
    joinedOn: '2021-06-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0048',
    name: 'Saad Malik',
    department: 'Engineering',
    title: 'Cloud Engineer',
    joinedOn: '2023-09-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0049',
    name: 'Hina Qureshi',
    department: 'Engineering',
    title: 'Software Engineer Intern',
    joinedOn: '2024-01-15',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0050',
    name: 'Waseem Akram',
    department: 'Engineering',
    title: 'Technical Lead',
    joinedOn: '2018-04-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },

  {
    id: 'EMP0051',
    name: 'Sadia Rauf',
    department: 'HR',
    title: 'Training Coordinator',
    joinedOn: '2021-09-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0002',
  },
  {
    id: 'EMP0052',
    name: 'Bilal Haider',
    department: 'HR',
    title: 'Compensation Analyst',
    joinedOn: '2022-03-08',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0002',
  },
  {
    id: 'EMP0053',
    name: 'Amina Sheikh',
    department: 'HR',
    title: 'Employee Relations Specialist',
    joinedOn: '2020-12-01',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0002',
  },
  {
    id: 'EMP0054',
    name: 'Rizwan Ali',
    department: 'HR',
    title: 'HR Business Partner',
    joinedOn: '2019-07-22',
    leftOn: '2023-08-15',
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0002',
  },

  {
    id: 'EMP0055',
    name: 'Sana Javed',
    department: 'Sales',
    title: 'Senior Account Executive',
    joinedOn: '2018-11-30',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0056',
    name: 'Adnan Khan',
    department: 'Sales',
    title: 'Sales Development Representative',
    joinedOn: '2023-04-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0057',
    name: 'Fiza Ahmed',
    department: 'Sales',
    title: 'Key Account Manager',
    joinedOn: '2020-01-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0058',
    name: 'Usman Siddiqui',
    department: 'Sales',
    title: 'Sales Operations Manager',
    joinedOn: '2021-05-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0003',
  },
  {
    id: 'EMP0059',
    name: 'Mariam Ali',
    department: 'Sales',
    title: 'Sales Intern',
    joinedOn: '2024-07-01',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0003',
  },

  {
    id: 'EMP0060',
    name: 'Hassan Raza',
    department: 'Finance',
    title: 'Senior Accountant',
    joinedOn: '2019-03-25',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0004',
  },
  {
    id: 'EMP0061',
    name: 'Ayesha Siddiqui',
    department: 'Finance',
    title: 'Budget Analyst',
    joinedOn: '2022-08-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0004',
  },
  {
    id: 'EMP0062',
    name: 'Tahir Mahmood',
    department: 'Finance',
    title: 'Tax Specialist',
    joinedOn: '2021-01-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0004',
  },
  {
    id: 'EMP0063',
    name: 'Nazia Khan',
    department: 'Finance',
    title: 'Accounts Payable Clerk',
    joinedOn: '2023-06-05',
    leftOn: null,
    employmentType: 'PartTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0004',
  },

  {
    id: 'EMP0064',
    name: 'Kashif Ali',
    department: 'Operations',
    title: 'Senior Operations Analyst',
    joinedOn: '2018-09-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0005',
  },
  {
    id: 'EMP0065',
    name: 'Saba Rizwan',
    department: 'Operations',
    title: 'Process Improvement Specialist',
    joinedOn: '2021-11-28',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0005',
  },
  {
    id: 'EMP0066',
    name: 'Fahad Sheikh',
    department: 'Operations',
    title: 'Logistics Coordinator',
    joinedOn: '2022-07-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0005',
  },
  {
    id: 'EMP0067',
    name: 'Amina Qureshi',
    department: 'Operations',
    title: 'Quality Assurance Coordinator',
    joinedOn: '2020-04-22',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0005',
  },

  {
    id: 'EMP0068',
    name: 'Zain Ali',
    department: 'Marketing',
    title: 'Digital Marketing Specialist',
    joinedOn: '2022-01-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0069',
    name: 'Sara Ahmed',
    department: 'Marketing',
    title: 'Brand Manager',
    joinedOn: '2021-08-30',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0070',
    name: 'Omar Khan',
    department: 'Marketing',
    title: 'Content Creator',
    joinedOn: '2023-03-12',
    leftOn: null,
    employmentType: 'Contract',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0071',
    name: 'Hina Malik',
    department: 'Marketing',
    title: 'Email Marketing Specialist',
    joinedOn: '2022-09-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0006',
  },
  {
    id: 'EMP0072',
    name: 'Asim Rauf',
    department: 'Marketing',
    title: 'Marketing Intern',
    joinedOn: '2024-06-15',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0006',
  },

  {
    id: 'EMP0073',
    name: 'Nida Ali',
    department: 'IT',
    title: 'Network Administrator',
    joinedOn: '2020-10-08',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0007',
  },
  {
    id: 'EMP0074',
    name: 'Saad Ahmed',
    department: 'IT',
    title: 'Database Administrator',
    joinedOn: '2019-12-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0007',
  },
  {
    id: 'EMP0075',
    name: 'Ayesha Khan',
    department: 'IT',
    title: 'IT Support Specialist',
    joinedOn: '2023-05-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0007',
  },
  {
    id: 'EMP0076',
    name: 'Fahad Sheikh',
    department: 'IT',
    title: 'Cloud Solutions Architect',
    joinedOn: '2021-07-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0007',
  },

  {
    id: 'EMP0077',
    name: 'Mariam Siddiqui',
    department: 'CustomerSuccess',
    title: 'Senior Customer Success Manager',
    joinedOn: '2018-06-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0008',
  },
  {
    id: 'EMP0078',
    name: 'Bilal Ahmed',
    department: 'CustomerSuccess',
    title: 'Customer Success Analyst',
    joinedOn: '2022-04-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0008',
  },
  {
    id: 'EMP0079',
    name: 'Sana Rizwan',
    department: 'CustomerSuccess',
    title: 'Customer Support Representative',
    joinedOn: '2023-08-25',
    leftOn: null,
    employmentType: 'PartTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0008',
  },
  {
    id: 'EMP0080',
    name: 'Usman Ali',
    department: 'CustomerSuccess',
    title: 'Customer Success Intern',
    joinedOn: '2024-03-01',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0008',
  },

  {
    id: 'EMP0081',
    name: 'Hassan Khan',
    department: 'Product',
    title: 'Senior Product Manager',
    joinedOn: '2019-09-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0009',
  },
  {
    id: 'EMP0082',
    name: 'Amina Sheikh',
    department: 'Product',
    title: 'Product Analyst',
    joinedOn: '2022-02-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0009',
  },
  {
    id: 'EMP0083',
    name: 'Tariq Ahmed',
    department: 'Product',
    title: 'UX Designer',
    joinedOn: '2021-10-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0009',
  },
  {
    id: 'EMP0084',
    name: 'Sara Ali',
    department: 'Product',
    title: 'Product Marketing Manager',
    joinedOn: '2020-12-08',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0009',
  },

  {
    id: 'EMP0085',
    name: 'Ayesha Rauf',
    department: 'Legal',
    title: 'Legal Assistant',
    joinedOn: '2022-06-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0010',
  },
  {
    id: 'EMP0086',
    name: 'Fahad Malik',
    department: 'Legal',
    title: 'Compliance Officer',
    joinedOn: '2021-04-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0010',
  },
  {
    id: 'EMP0087',
    name: 'Nida Khan',
    department: 'Legal',
    title: 'Contract Specialist',
    joinedOn: '2023-01-15',
    leftOn: null,
    employmentType: 'Contract',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0010',
  },

  {
    id: 'EMP0088',
    name: 'Omar Siddiqui',
    department: 'Engineering',
    title: 'Machine Learning Engineer',
    joinedOn: '2022-11-08',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0089',
    name: 'Hina Ahmed',
    department: 'Engineering',
    title: 'Security Engineer',
    joinedOn: '2021-03-25',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0090',
    name: 'Saad Ali',
    department: 'Engineering',
    title: 'Platform Engineer',
    joinedOn: '2023-07-18',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0091',
    name: 'Amina Khan',
    department: 'Engineering',
    title: 'Frontend Developer',
    joinedOn: '2022-05-30',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0092',
    name: 'Tariq Sheikh',
    department: 'Engineering',
    title: 'Backend Developer',
    joinedOn: '2021-12-12',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0093',
    name: 'Sara Rizwan',
    department: 'Engineering',
    title: 'Mobile Developer',
    joinedOn: '2023-04-05',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0094',
    name: 'Usman Ahmed',
    department: 'Engineering',
    title: 'QA Engineer',
    joinedOn: '2020-08-22',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0095',
    name: 'Fiza Ali',
    department: 'Engineering',
    title: 'DevOps Engineer',
    joinedOn: '2022-09-14',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0096',
    name: 'Hassan Khan',
    department: 'Engineering',
    title: 'Software Engineer Intern',
    joinedOn: '2024-08-01',
    leftOn: null,
    employmentType: 'Intern',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0097',
    name: 'Nida Sheikh',
    department: 'Engineering',
    title: 'Data Scientist',
    joinedOn: '2021-06-28',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0098',
    name: 'Bilal Rizwan',
    department: 'Engineering',
    title: 'Site Reliability Engineer',
    joinedOn: '2020-02-10',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Karachi', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0099',
    name: 'Ayesha Ahmed',
    department: 'Engineering',
    title: 'Full Stack Developer',
    joinedOn: '2023-01-20',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Lahore', country: 'PK' },
    managerId: 'EMP0001',
  },
  {
    id: 'EMP0100',
    name: 'Omar Ali',
    department: 'Engineering',
    title: 'Senior Software Engineer',
    joinedOn: '2019-11-15',
    leftOn: null,
    employmentType: 'FullTime',
    location: { city: 'Islamabad', country: 'PK' },
    managerId: 'EMP0001',
  },
];